# Generated by Django 3.0.8 on 2020-07-08 13:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True, verbose_name='Desconto(R$)')),
                ('manufacturer_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Manufatura ID')),
                ('product', models.CharField(default='', max_length=20, verbose_name='Produto')),
                ('product_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Produto ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True, verbose_name='Quantidade')),
                ('store_id', models.CharField(default='', max_length=20, verbose_name='Produto')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True, verbose_name='Valor Total (R$)')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True, verbose_name='Valor (R$)')),
                ('criadoEm', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificadoEm', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['product'],
            },
        ),
    ]
