# Generated by Django 3.0.8 on 2020-07-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='product',
            field=models.CharField(default='', max_length=50, verbose_name='Produto'),
        ),
    ]
