# Generated by Django 3.0.8 on 2020-07-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200708_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='criadoEm',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='modificadoEm',
        ),
    ]
