# Generated by Django 3.0.8 on 2020-07-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200708_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={},
        ),
    ]
