# Generated by Django 3.0.8 on 2020-07-13 12:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200710_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalVendido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('product_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Produto ID')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True, verbose_name='Valor Total do dia desse produto(R$)')),
            ],
        ),
    ]
